// <auto-generated />
using BuecherVerwaltungEmpty.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuecherVerwaltungEmpty.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250524093753_AddIstGelesen")]
    partial class AddIstGelesen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("BuecherVerwaltungEmpty.Data.Buch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IstGelesen")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Jahr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Verlag")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Buecher");
                });
#pragma warning restore 612, 618
        }
    }
}
